# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: ci

on:
  push:
  pull_request:

jobs:
  ci:
    strategy:
      matrix:
        include:
          # - {os: macOS-latest,   r: 'release'}
          # - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release', depends_only: TRUE}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}
          - {os: ubuntu-latest,   r: 'oldrel-2'}
          - {os: ubuntu-latest,   r: 'oldrel-3'}

    runs-on: ${{ matrix.os }}

    env:
      _R_CHECK_FORCE_SUGGESTS_: "false"
      _R_CHECK_TESTS_NLINES_: 0
      R_NOT_CRAN: true
      R_GH: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Get Script
        run: curl -OLs https://eddelbuettel.github.io/r-ci/run.sh && chmod 0755 run.sh

      - name: Bootstrap
        run: ./run.sh bootstrap

      - name: Dependencies
        run: ./run.sh install_all

      - name: tinytest 1.4.0
        run: Rscript -e "remotes::install_github('markvanderloo/tinytest/pkg')"

      - name: tinyviztest
        run: Rscript -e "remotes::install_github('vincentarelbundock/tinyviztest')"

        run: ./run.sh install_source TMB

      - name: glmmTMB source
        run: ./run.sh install_source glmmTMB

      - name: Test
        run: ./run.sh run_tests