# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: website

on:
  push:
  pull_request:

env:
  _R_CHECK_FORCE_SUGGESTS_: "false"
  _R_CHECK_TESTS_NLINES_: 0
  R_NOT_CRAN: true
  R_GH: true
  GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

jobs:
  ci:
    strategy:
      matrix:
        include:
          - {os: ubuntu-latest,   r: 'release'}

    runs-on: ${{ matrix.os }}

    env:
      _R_CHECK_FORCE_SUGGESTS_: "false"
      _R_CHECK_TESTS_NLINES_: 0
      R_NOT_CRAN: true
      R_GH: true
      GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

    steps:
      - uses: actions/checkout@v3

      - name: Get Script
        run: curl -OLs https://eddelbuettel.github.io/r-ci/run.sh && chmod 0755 run.sh

      - name: Bootstrap
        run: ./run.sh bootstrap
          
      - name: Quarto
        run: sudo curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb;sudo apt-get install gdebi-core;sudo gdebi quarto-linux-amd64.deb

      - name: png (for svglite)
        run: sudo apt update -qq && sudo apt install --yes --no-install-recommends libpng-dev
        
      - name: svglite from source
        run: Rscript -e "bspm::disable();install.packages('svglite', from = 'source');bspm::enable()"

      - name: TMB
        run: ./run.sh install_source TMB

      - name: glmmTMB source
        run: ./run.sh install_source glmmTMB

      - name: Matrix source
        run: ./run.sh install_source Matrix

      - name: Dependencies
        run: ./run.sh install_all

      - name: cmdstanr
        run: Rscript -e 'install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))'

      - name: install marginalleffects
        run: R CMD INSTALL .

      - name: deploy website
        run: make deploy
          
      # - name: Coverage
      #   if: ${{ matrix.os == 'ubuntu-latest' }}
      #   run: ./run.sh coverage