# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: website

on:
  push:
  pull_request:

env:
  _R_CHECK_FORCE_SUGGESTS_: "false"
  _R_CHECK_TESTS_NLINES_: 0
  R_NOT_CRAN: true
  R_GH: true
  GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

jobs:
  ci:
    strategy:
      matrix:
        include:
          - {os: ubuntu-latest,   r: 'release'}

    runs-on: ${{ matrix.os }}

    env:
      _R_CHECK_FORCE_SUGGESTS_: "false"
      _R_CHECK_TESTS_NLINES_: 0
      R_NOT_CRAN: true
      R_GH: true
      GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

    steps:
      - uses: actions/checkout@v3

      - name: Get Script
        run: curl -OLs https://eddelbuettel.github.io/r-ci/run.sh && chmod 0755 run.sh

      - name: Bootstrap
        run: ./run.sh bootstrap
          
      - name: Quarto
        run: curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb;sudo dpkg -i quarto-linux-amd64.deb

      - name: Dependencies
        run: ./run.sh install_all

      - name: cmdstanr
        run: Rscript -e 'install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")));cmdstanr::install_cmdstan()'

      - name: install marginalleffects
        run: R CMD INSTALL .

      - name: deploy website
        run: Rscript -e "source(here::here('book/utils.R'));deploy_book()"
